### ISSUE TITLE
Remarks about 'PSVersionMappingTable.json'

### ISSUE THREAD

**Issue by LaurentDardenne** [janegilring/PSVersion#3]
The version 1 of Powershell do not contains a $PsVersionTable variable and the remoting is not supported.
The version 2 of Powershell works under XP,Vista and 2003  (see https://support.microsoft.com/en-us/kb/968929).

Is it planned a _ConvertTo-PsVersion_ function ?

``` Powershell
'1.0'|ConvertTo-PsVersion
```

**Comment by janegilring** [comment]
That's a valid point, I added version 1 to the table mostly for reference purposes when using Get-PSVersion -ListVersion. 
I'm not sure if supporting 1.0 for remote inventory is worth doing, but let me know if that's something you would find useful.

**Comment by LaurentDardenne** [comment]
I understand better his presence, I rarely remember the OS supported by powershell :-)
