### ISSUE TITLE
PSVersion module failed to install in Linux OS

### ISSUE THREAD

**Issue by MaximoTrinidad** [janegilring/PSVersion#5]
I know is too soon but here I go.  This is a good example of an available module in the repository but won't install in Linux.
:)

It would be nice to have it available for PowerShell Open Source.
- Ubuntu 16.04.1 LTS Desktop
- PowerShell 6.0.0-alpha.10

![psversionissuelinux](https://cloud.githubusercontent.com/assets/19892435/18896998/5b00569c-84f4-11e6-8c60-7875cc5b67ef.png)

**Comment by janegilring** [comment]
Thanks for submitting the issue, Max. I hadn't really thought about testing the module on Linux, but we have to make that work too. I`ll follow up on this subject later on.

**Comment by janegilring** [comment]
I  just tested installing the module on PowerShell Core beta 3 running on Ubuntu 16.04, where it worked fine. I'll close this issue for know, feel free to re-open if you encounter any issues.
