### ISSUE TITLE
PSVersion "PSVersionFriendlyName" shows unknown

### ISSUE THREAD

**Issue by MaximoTrinidad** [janegilring/PSVersion#6]
This is just an observation.  
I'm currently using a Windows Insider Windows 10 newest build:
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.14931 N/A Build 14931

When executing the Get-PSVersion show:

PS C:\WINDOWS\system32> Get-PSversion
PSComputerName   PSVersion             PSVersionFriendlyName

---

MTRINIDADLT2        5.1.14931.1000    **Unknown**

**Comment by janegilring** [comment]
Thanks for the feedback. I haven't had time to follow versions for the Insider Previews, but feel free to submit pull request against the [version mapping table](https://github.com/janegilring/PSVersion/blob/master/PSVersionMappingTable.json).
