### ISSUE TITLE
PowerShell Core Beta - Get-PSVersion "PSVersionFriendlyName" shows unknown 

### ISSUE THREAD

**Issue by MaximoTrinidad** [janegilring/PSVersion#7]
Apologies as the initial issue I posted shows an example with Windows PowerShell.  Well, it shows also in the latest PowerShell Core Beta 4.

Get-PSVersion is showing "unknown"under the PSVersionFriendlyName column.

![psgetver_unkn_2017-07-14_9-30-07](https://user-images.githubusercontent.com/19892435/28214287-a2d2f8b4-6877-11e7-8318-6fbe0ec72202.jpg)

**Comment by janegilring** [comment]
Fixed by https://github.com/janegilring/PSVersion/commit/3a3b4f00cc739be21da38d1d2b6f6817ad7511c0
